### ISSUE TITLE
Add `username` field to the User.

### ISSUE THREAD

**Issue by azizunsal** [tahafurkanunsal/SpringBoot-MySQL-Project-2#24]
`User` classina yeni alanlar eklenmeli

1. `username` alani eklenecek. Bu `username` __unique__ olmali; yani bir kullanici diger bir kullanicidan ayirt eden bir ozellik olmali.
2. Address alani eklenmeli.
3. Daha sonra bu `username` alanina gore User'i cekecek bir API de eklenmeli.

**Comment by tahafurkanunsal** [comment]
ok
