### ISSUE TITLE
Do not send all attributes of the User to the client.

### ISSUE THREAD

**Issue by azizunsal** [tahafurkanunsal/SpringBoot-MySQL-Project-2#25]
Client'a gonderilen User icerisinde database'de tutulan tum alanlar olmamali. (Mesela password gibi bir alan tutulabilirdi ornek olarak ve GET isteginde tum User'lari donen API, kullanicilarin password'lerini gondermemeli. Bunu yeni ekleyecegin `address` alani icin yapacaksin.)

**Comment by tahafurkanunsal** [comment]
ok
